apiVersion: v2
name: clever
description: A Helm chart for Kubernetes

type: application

version: 0.1.1

appVersion: "1.16.0"

dependencies:
  - name: mongodb
    version: 15.6.18
    repository: https://charts.bitnami.com/bitnami
