appName: clever
namespace: tidb-hackathon

image:
  repository: docker.yesidlopez.de/study_buddy
  pullPolicy: IfNotPresent
  tag: "1.3.0"

service:
  type: LoadBalancer
  port: 80

readinessProbe:
  httpGet:
    path: /health
    port: http

mongodb:
  auth:
    enabled: false

postgresql:
  global:
    postgresql:
      auth:
        postgresPassword: clever_trulens
  primary:
    service:
      type: LoadBalancer
