appName: clever
namespace: tidb-hackathon

image:
  repository: docker.yesidlopez.de/study_buddy
  pullPolicy: IfNotPresent
  tag: "1.1.5"

service:
  type: LoadBalancer
  port: 80

readinessProbe:
  httpGet:
    path: /health
    port: http

mongodb:
  auth:
    enabled: false
  service:
    type: LoadBalancer
