services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8000:80"

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: study_buddy
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  trulens-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: clever_truelens

  trulens-dashboard:
    build:
      context: trulens_dashboard
    ports:
      - "8501:8501"
    env_file:
      - .env
      
